general {
    lock_cmd = pidof hyprlock || ~/.local/bin/lock.sh
    before_sleep_cmd = loginctl lock-session && ~/.local/bin/dpms-handler.sh off
    after_sleep_cmd = ~/.local/bin/dpms-handler.sh on
}

# Set brightness
listener {
    timeout = 900
    on-timeout = brightnessctl -s set 5s
    on-resume = brightnessctl -r
}

# Lock screen
listener {
    timeout = 3600
    on-timeout = loginctl lock-session
}

# Turn off display (DPMS)
listener {
    timeout = 7200
    on-timeout = ~/.local/bin/dpms-handler.sh off
    on-resume = ~/.local/bin/dpms-handler.sh on && sleep 0.5 && brightnessctl -r
}