# Reference: https://github.com/mahaveergurjar/Hyprlock-Dots
# Thanks to @mahaveergurjar for the original config and inspiration

# █ █ █▄█ █▀█ █▀█ █   █▀█ █▀▀ █▄▀
# █▀█  █  █▀▀ █▀▄ █▄▄ █▄█ █▄▄ █ █

source = ~/.local/state/haku_theme/hyprland-style.conf

# GENERAL
general {
    hide_cursor = true
    ignore_empty_input = true
    text_trim = true
}

# BACKGROUND
background {
    monitor = 
    path = screenshot
    blur_passes = 2
    contrast = 1.2
    brightness = 0.5
    vibrancy = 0.1696
    vibrancy_darkness = 0
}


# TIME HR
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%H")"
    color = $accent_color
    shadow_size = 3
    shadow_color = rgb(0,0,0)
    shadow_boost = 1.4
    font_size = 80
    font_family = $font_family extraBold
    position = 0, 120
    halign = center
    valign = center
    zindex = 5
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%M")"
    color = rgba(255, 255, 255, 0.8)
    font_size = 80
    font_family = $font_family extraBold
    position = 0, 20
    halign = center
    valign = center
    zindex = 5
}

# DATE
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%d %b %A")"
    color = $accent_color
    font_size = 11
    font_family = $font_family extraBold
    position = 0, -60
    halign = center
    valign = center
    zindex = 5
}

# USER (TOP)
label {
    monitor =
    text = Hi there, $USER
    color = $accent_color
    font_size = 12
    font_family = $font_family extraBold
    position = 0, 320
    halign = center
    valign = center
    zindex = 5
}


# INPUT FIELD
input-field {
    monitor =
    size = 160, 50
    outline_thickness = 0
    outer_color = $accent_color
    dots_size = 0.3
    dots_spacing = 0.2
    dots_center = true
    inner_color = rgba(255, 255, 255, 0.05)
    font_color = $accent_color
    fade_on_empty = false
    placeholder_text = <i> Use Me ;) </i>
    hide_input = false
    fail_color = rgba(204, 34, 34, 0.5)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    position = 0, -150
    halign = center
    valign = center
    zindex = 20
}

# BOX (CENTER)
shape {
    monitor =
    size = 260, 460
    color = rgba(0, 0, 0, 0.3)
    rounding = 64
    position = 0, 0
    halign = center
    valign = center
}

# BOTTOM TEXT
label {
    monitor =
    text = Have a nice day!
    color = $accent_color
    font_size = 12
    font_family = $font_family extraBold
    position = 0, -320
    halign = center
    valign = center
    zindex = 5
}
